name       : spice-up
version    : 1.8.0
release    : 5
source     :
    - https://github.com/Philip-Scott/Spice-up/archive/1.8.0.tar.gz : e55e1a10e54bf8029b19c22f8265df7fd974baacaf58f67e94e88a0b34c9586e
license    : GPL-3.0-only
component  : office
summary    : Create simple and beautiful presentations on the Linux desktop
description: |
    Spice-up is a modern and intuitive desktop presentation app based upon SpiceOfDesign's presentation concept. Built from the ground up for elementary OS, it gives you everything you need to create simple and beautiful presentations.
builddeps  :
    - pkgconfig(gee-1.0)
    - pkgconfig(granite)
    - pkgconfig(gudev-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libevdev)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    sed -i "6d" src/CMakeLists.txt # disable tests
    %cmake -DCMAKE_INSTALL_PREFIX=/usr/
build      : |
    %make -j1
install    : |
    %make_install
